services:
  - type: web
    name: spotify-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Spotify_BE.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Spotify_BE.settings
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: SECRET_KEY_JWT
        value: your-jwt-secret-key
      - key: DEBUG
        value: false
      - key: DB_NAME
        value: your_db_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_HOST
        value: your_db_host
      - key: AWS_ACCESS_KEY_ID
        value: your_aws_key_id
      - key: AWS_SECRET_ACCESS_KEY
        value: your_aws_secret_key
      - key: AWS_STORAGE_BUCKET_NAME
        value: your_s3_bucket
      - key: AWS_S3_REGION_NAME
        value: ap-southeast-1
      - key: RD_URL
        value: your_redis_url
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret
